### ISSUE TITLE
Updating oh-my-zsh installations

### ISSUE THREAD

**Issue by alexbartok** [acme/puppet-acme-oh-my-zsh#2]
Hi,
is there a way I can have the module automatically update all oh-my-zsh installations?

Thanks!

**Comment by acme** [comment]
Thanks for the suggestion. I've just released a new version:
https://forge.puppetlabs.com/acme/ohmyzsh
This has the new feature:
`ohmyzsh::upgrade { 'acme': }`
Does that work for you?

**Comment by alexbartok** [comment]
Yes it does! thanks! :+1:
